require('dotenv').config();

module.exports = {
    apps: [
        {
            name: 'bbw',
            script: './dist/main.js', // Path to the entry point of your app
            watch: true,
            instances: 1, // Adjust based on your environment
            autorestart: true,
            env: {
                NODE_ENV: process.env.NODE_ENV,
                APP_PORT: process.env.APP_PORT,
                APP_NAME: process.env.APP_NAME,
                API_PREFIX: process.env.API_PREFIX,
                APP_FALLBACK_LANGUAGE: process.env.APP_FALLBACK_LANGUAGE,
                APP_HEADER_LANGUAGE: process.env.APP_HEADER_LANGUAGE,
                FRONTEND_DOMAIN: process.env.FRONTEND_DOMAIN,
                BACKEND_DOMAIN: process.env.BACKEND_DOMAIN,
                DATABASE_TYPE: process.env.DATABASE_TYPE,
                DATABASE_HOST: process.env.DATABASE_HOST,
                DATABASE_PORT: process.env.DATABASE_PORT,
                DATABASE_USERNAME: process.env.DATABASE_USERNAME,
                DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
                DATABASE_NAME: process.env.DATABASE_NAME,
                DATABASE_SYNCHRONIZE: process.env.DATABASE_SYNCHRONIZE,
                DATABASE_MAX_CONNECTIONS: process.env.DATABASE_MAX_CONNECTIONS,
                DATABASE_SSL_ENABLED: process.env.DATABASE_SSL_ENABLED,
                DATABASE_REJECT_UNAUTHORIZED: process.env.DATABASE_REJECT_UNAUTHORIZED,
                DATABASE_CA: process.env.DATABASE_CA,
                DATABASE_KEY: process.env.DATABASE_KEY,
                DATABASE_CERT: process.env.DATABASE_CERT,
                FILE_DRIVER: process.env.FILE_DRIVER,
                ACCESS_KEY_ID: process.env.ACCESS_KEY_ID,
                SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY,
                AWS_S3_REGION: process.env.AWS_S3_REGION,
                AWS_DEFAULT_S3_BUCKET: process.env.AWS_DEFAULT_S3_BUCKET,
                MAIL_HOST: process.env.MAIL_HOST,
                MAIL_PORT: process.env.MAIL_PORT,
                MAIL_USER: process.env.MAIL_USER,
                MAIL_PASSWORD: process.env.MAIL_PASSWORD,
                MAIL_IGNORE_TLS: process.env.MAIL_IGNORE_TLS,
                MAIL_SECURE: process.env.MAIL_SECURE,
                MAIL_REQUIRE_TLS: process.env.MAIL_REQUIRE_TLS,
                MAIL_DEFAULT_EMAIL: process.env.MAIL_DEFAULT_EMAIL,
                MAIL_DEFAULT_NAME: process.env.MAIL_DEFAULT_NAME,
                MAIL_CLIENT_PORT: process.env.MAIL_CLIENT_PORT,
                AUTH_JWT_SECRET: process.env.AUTH_JWT_SECRET,
                AUTH_JWT_TOKEN_EXPIRES_IN: process.env.AUTH_JWT_TOKEN_EXPIRES_IN,
                AUTH_REFRESH_SECRET: process.env.AUTH_REFRESH_SECRET,
                AUTH_REFRESH_TOKEN_EXPIRES_IN: process.env.AUTH_REFRESH_TOKEN_EXPIRES_IN,
                FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
                FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
                GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
                GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
                APPLE_APP_AUDIENCE: process.env.APPLE_APP_AUDIENCE,
                TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
                TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
                WORKER_HOST: process.env.WORKER_HOST,
            },
        },
    ],
};
